### ISSUE TITLE
rebase to k8s v0.14+

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#197]
With the rebase we'll pick up a few nice bits:
- pod binding annotations (#162)
- network plugin API
- persistent volumes API
- kubelet push to master (vs master poll kubelet)
- thread-per-pod in kubelet
- cadvisor integrated into kubelet (#18)
- better static pod support in kubelet (mirror pods) ((we don't use this ... yet))
- many bug fixes

TODO:
- [x] revisit patch #129 (capture/monitor kubelet event stream)
- [x] ~~network plugins directory is statically defined, outside the mesos sandbox~~ see #203
- [x] scheduler service publisher no longer handles multiple masters
- [x] scheduler endpoints aren't versioned, apiserver is complaining/rejecting
- [x] eliminate "profile" tag/package since `profiling` is now a cmd flag
  - 'profiling' is a flag for scheduler -- all the time
  - 'profile' tag currently determine whether profiling support is compiled into k8sm-executor
- [x] new flags for kubelet-executor: scheduler should pass some of them through
- [x] scheduler debug handlers need attachment to serveMux
- [x] kubelet validation of FQDN fails against API server since mesos slaves are registered with hostname=their.ip.address
  - slaves on GCE are actually started with `--hostname=10.150.52.19`
- [x] node controller / provider implementation
  - [x] mesos cloud provider should be a team player: report slave resources so that the node controller does not have to guess
  - [x] GetNodeResources is super-inefficient, should probably share a cache with List()
  - [x] if slave is running, but there is no kubelet, default "static" capacity reports resources that do not reflect reality
- [x] backport unsafe "master" reference in mesos/client provider implementation to release-0.4
- [x] kubelet wants to be configured with cloudprovider (why??)
- [x] documentation
  - [x] README.md (flag changes)
  - [x] update "current" kubernetes version
  - [x] ~~update profiling docs~~ #205
  - [x] ha docs: etcd flags don't matter for executor
  - [x] ~~update arch diagram: kubelet and proxy feed from apiserver, not etcd~~ #206

**Comment by jdef** [comment]
k8sm-executor DATA RACE:
```
I0403 04:32:13.796113   15739 service.go:433] killing proxy process..
==================
WARNING: DATA RACE
Read by goroutine 79:
  github.com/mesosphere/kubernetes-mesos/pkg/executor/service.func·005()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/executor/service/service.go:434 +0x9a
  github.com/mesosphere/kubernetes-mesos/pkg/executor/service.func·006()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/executor/service/service.go:448 +0x465

Previous write by goroutine 74:
  os/exec.(*Cmd).Start()
      /usr/local/go/src/os/exec/exec.go:311 +0xed1
  github.com/mesosphere/kubernetes-mesos/pkg/executor/service.(*kubeletExecutor).runProxyService()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/executor/service/service.go:452 +0x1550
  github.com/mesosphere/kubernetes-mesos/pkg/executor/service.*kubeletExecutor.(github.com/mesosphere/kubernetes-mesos/pkg/executor/service.runProxyService)·fm()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/executor/service/service.go:355 +0x34
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.func·003()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:107 +0x61
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:108 +0xbf
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Forever()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:92 +0x48

Goroutine 79 (running) created at:
  github.com/mesosphere/kubernetes-mesos/pkg/executor/service.(*kubeletExecutor).runProxyService()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/executor/service/service.go:448 +0x152a
  github.com/mesosphere/kubernetes-mesos/pkg/executor/service.*kubeletExecutor.(github.com/mesosphere/kubernetes-mesos/pkg/executor/service.runProxyService)·fm()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/executor/service/service.go:355 +0x34
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.func·003()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:107 +0x61
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:108 +0xbf
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Forever()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:92 +0x48
```

**Comment by jdef** [comment]
another kubelet (upstream) data race:
```
==================
WARNING: DATA RACE
Write by goroutine 20:
  github.com/google/cadvisor/storage/memory.(*containerStorage).AddStats()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/google/cadvisor/storage/memory/memory.go:41 +0x1e1
  github.com/google/cadvisor/storage/memory.(*InMemoryStorage).AddStats()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/google/cadvisor/storage/memory/memory.go:87 +0x2b3
  github.com/google/cadvisor/manager.(*containerData).updateStats()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/google/cadvisor/manager/container.go:319 +0xb23
  github.com/google/cadvisor/manager.(*containerData).housekeepingTick()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/google/cadvisor/manager/container.go:241 +0x3e
  github.com/google/cadvisor/manager.(*containerData).housekeeping()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/google/cadvisor/manager/container.go:195 +0x2bd

Previous read by goroutine 64:
  github.com/google/cadvisor/manager.(*manager).GetFsInfo()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/google/cadvisor/manager/manager.go:585 +0x332
  github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/cadvisor.(*cadvisorClient).DockerImagesFsInfo()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/cadvisor/cadvisor_linux.go:117 +0xad
  github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*realImageManager).GarbageCollect()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/image_manager.go:176 +0x97
  github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.func·007()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/kubelet.go:517 +0x91
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.func·003()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:107 +0x61
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:108 +0xbf
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Forever()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:92 +0x48

Goroutine 20 (running) created at:
  github.com/google/cadvisor/manager.(*containerData).Start()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/google/cadvisor/manager/container.go:69 +0x52
  github.com/google/cadvisor/manager.(*manager).createContainer()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/google/cadvisor/manager/manager.go:685 +0x9dd
  github.com/google/cadvisor/manager.(*manager).Start()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/google/cadvisor/manager/manager.go:205 +0x1b8
  github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/cadvisor.New()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/cadvisor/cadvisor_linux.go:59 +0x307
  github.com/mesosphere/kubernetes-mesos/pkg/executor/service.(*KubeletExecutorServer).Run()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/executor/service/service.go:130 +0x63d
  main.func·002()
```

**Comment by jdef** [comment]
data race in controller-manager (upstream):
```
==================
WARNING: DATA RACE
Write by goroutine 28:
  github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/controller.func·001()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/controller/nodecontroller.go:152 +0x7c
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.func·003()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:107 +0x61
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:108 +0xbf
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Forever()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:92 +0x48

Previous write by goroutine 30:
  github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/controller.func·003()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/controller/nodecontroller.go:167 +0x7c
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.func·003()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:107 +0x61
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:108 +0xbf
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Forever()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:92 +0x48
```

**Comment by jdef** [comment]
node-controller hates our cloud provider's capacity reporting:
```
I0403 15:54:13.857719   29806 nodecontroller.go:227] Create node in registry: 10.72.72.178
E0403 15:54:13.861610   29806 nodecontroller.go:230] Create node 10.72.72.178 error: Node "10.72.72.178" is invalid: status.Capacity: required value
I0403 15:54:13.861656   29806 nodecontroller.go:227] Create node in registry: 10.150.52.19
E0403 15:54:13.864984   29806 nodecontroller.go:230] Create node 10.150.52.19 error: Node "10.150.52.19" is invalid: status.Capacity: required value
I0403 15:54:13.865037   29806 nodecontroller.go:227] Create node in registry: 10.22.211.18
E0403 15:54:13.868183   29806 nodecontroller.go:230] Create node 10.22.211.18 error: Node "10.22.211.18" is invalid: status.Capacity: required value
```

**Comment by jdef** [comment]
E0403 18:17:30.450092   13835 publish.go:45] Can't create scheduler endpoints: invalid update object, missing resource version: &{{ } {k8sm-scheduler  default    0001-01-01 00:00:00 +0000 UTC <nil> map[] map[]} [{[{10.223.113.227 <nil>}] [{ 10251 TCP}]}]}

**Comment by jdef** [comment]
scheduler data race on driver error:
```
I0404 02:39:04.919255   31446 scheduler.go:1093] Aborting driver, got error ' Failed to send message mesos.internal.LaunchTasksMessage: Post http://10.223.113.227:5050/master/mesos.internal.LaunchTasksMessa
ge: dial tcp 10.223.113.227:5050: connection refused '
I0404 02:39:04.919260   31446 http_transporter.go:107] Sending message to master@10.223.113.227:5050 via http
I0404 02:39:04.919311   31446 scheduler.go:860] Aborting framework [&FrameworkID{Value:*20150401-125214-3815890698-5050-2036-0000,XXX_unrecognized:[],}]
I0404 02:39:04.919415   31446 scheduler.go:815] Stopping the scheduler driver
I0404 02:39:04.919435   31446 http_transporter.go:343] libproc target URL http://10.223.113.227:5050/master/mesos.internal.LaunchTasksMessage
I0404 02:39:04.921297   31446 messenger.go:166] Sending message mesos.internal.UnregisterFrameworkMessage to master@10.223.113.227:5050
I0404 02:39:04.922329   31446 ha.go:88] scheduler process entered fin stage
I0404 02:39:04.922456   31446 proc.go:176] terminating process 1
==================
WARNING: DATA RACE
Write by goroutine 60:
  runtime.closechan()
      /usr/local/go/src/runtime/chan.go:257 +0x0
  github.com/mesosphere/kubernetes-mesos/pkg/proc.(*procImpl).End()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/proc/proc.go:177 +0x22d
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha.(*SchedulerProcess).End()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha/ha.go:89 +0x182
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha.func·002()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha/ha.go:116 +0x196

Previous read by goroutine 56:
  runtime.chansend()
      /usr/local/go/src/runtime/chan.go:83 +0x0
  github.com/mesosphere/kubernetes-mesos/pkg/proc.(*procImpl).doLater()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/proc/proc.go:152 +0x3ec
  github.com/mesosphere/kubernetes-mesos/pkg/proc.(*procImpl).Do()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/proc/proc.go:161 +0x51
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha.(*SchedulerProcess).Do()
      <autogenerated>:3 +0x8d
  github.com/mesosphere/kubernetes-mesos/pkg/proc.(*processAdapter).Do()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/proc/proc.go:198 +0x2af
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha.(*SchedulerProcess).Error()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha/ha.go:204 +0x1bc
  github.com/mesos/mesos-go/scheduler.(*MesosSchedulerDriver).error()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesos/mesos-go/scheduler/scheduler.go:1099 +0x578
  github.com/mesos/mesos-go/scheduler.(*MesosSchedulerDriver).frameworkErrorRcvd()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesos/mesos-go/scheduler/scheduler.go:632 +0x1f1
  github.com/mesos/mesos-go/scheduler.*MesosSchedulerDriver.(github.com/mesos/mesos-go/scheduler.frameworkErrorRcvd)·fm()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesos/mesos-go/scheduler/scheduler.go:242 +0x52
  github.com/mesos/mesos-go/messenger.(*MesosMessenger).decodeLoop()
      /pkg/src/github.com/mesosphere/kubernetes-mesos/_build/src/github.com/mesos/mesos-go/messenger/messenger.go:350 +0x9b3
```

**Comment by jdef** [comment]
kubelet attempts to use cloud provider to resolve something, complains that it's not configured:
```
E0404 12:47:05.593531   23508 standalone.go:180] Get http://localhost:5050/state.json: dial tcp 127.0.0.1:5050: connection refused
E0404 12:47:07.510612   23508 kubelet.go:1949] Cannot get host IP: Host IP unknown; known addresses: []
E0404 12:47:17.514730   23508 kubelet.go:1949] Cannot get host IP: Host IP unknown; known addresses: []
E0404 12:47:27.520289   23508 kubelet.go:1949] Cannot get host IP: Host IP unknown; known addresses: []
```

**Comment by jdef** [comment]
another scheduler data race:
```
WARNING: DATA RACE
Write by goroutine 61:
  runtime.closechan()
      /usr/local/go/src/runtime/chan.go:257 +0x0
  github.com/mesosphere/kubernetes-mesos/pkg/proc.(*procImpl).End()
      /snapshot/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/proc/proc.go:177 +0x22d
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha.(*SchedulerProcess).End()
      /snapshot/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha/ha.go:89 +0x182
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha.func·002()
      /snapshot/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha/ha.go:116 +0x196

Previous read by goroutine 56:
  runtime.chansend()
      /usr/local/go/src/runtime/chan.go:83 +0x0
  github.com/mesosphere/kubernetes-mesos/pkg/proc.(*procImpl).doLater()
      /snapshot/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/proc/proc.go:152 +0x3ec
  github.com/mesosphere/kubernetes-mesos/pkg/proc.(*procImpl).Do()
      /snapshot/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/proc/proc.go:161 +0x51
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha.(*SchedulerProcess).Do()
      <autogenerated>:3 +0x8d
  github.com/mesosphere/kubernetes-mesos/pkg/proc.(*processAdapter).Do()
      /snapshot/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/proc/proc.go:198 +0x2af
  github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha.(*SchedulerProcess).ResourceOffers()
      /snapshot/_build/src/github.com/mesosphere/kubernetes-mesos/pkg/scheduler/ha/ha.go:168 +0x1be
  github.com/mesos/mesos-go/scheduler.(*MesosSchedulerDriver).resourcesOffered()
      /snapshot/_build/src/github.com/mesos/mesos-go/scheduler/scheduler.go:504 +0xa54
  github.com/mesos/mesos-go/scheduler.*MesosSchedulerDriver.(github.com/mesos/mesos-go/scheduler.resourcesOffered)·fm()
      /snapshot/_build/src/github.com/mesos/mesos-go/scheduler/scheduler.go:237 +0x52
  github.com/mesos/mesos-go/messenger.(*MesosMessenger).decodeLoop()
      /snapshot/_build/src/github.com/mesos/mesos-go/messenger/messenger.go:350 +0x9b3
```

**Comment by jdef** [comment]
from scheduler logs:
```
E0405 02:35:15.077220   24250 plugin.go:797] pod reconciliation does not support updates; not yet implemented
```

**Comment by timothysc** [comment]
@jdef so imho this is reverse to trying to push the code into upstream k8's.  This seems like a lot of extra work to rebase vs piecemeal integration upstream.

**Comment by jdef** [comment]
@timothysc hopefully, as we spec out what the final upstreamed integration will look like, the project shouldn't have to remain in this position. in the meantime, we want a working distribution running on a very recent k8s.

**Comment by timothysc** [comment]
@jdef, 'as we spec out what the final upstreamed integration will look like'... is there a hold-up there? Upstream k8's is very receptive to changes, so even if it's not complete I'm confident they would change quickly.

**Comment by jdef** [comment]
@timothysc I'm the hold up WRT the spec :) My task this week is to propose a home for the k8sm scheduler/executor components, how they'll fit into the k8s distribution, and get buy-in from the k8s team.

**Comment by chenjunsheng** [comment]
ok
