### ISSUE TITLE
allow multiple k8sm frameworks w/ different framework names to run at the same time

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#201]
TODOs:
- [x] `framework_name` should be configurable (and not hard-coded). the currently hardcoded value should become the default
- [ ] variable path to store framework ID in etcd (should depend on the framework name)
- [ ] probably want framework name validation (needs to be a DNS label, without '.' chars)
  - [ ] should probably match apiserver `cluster_name` parameter
  - [ ] drives default value for scheduler `cluster_domain` parameter: `{framework_name}.mesos`
- [ ] document `framework_name` rules someplace, link to it from ha docs

**Comment by jdef** [comment]
may want to hold off on this for now because running multiple k8s frameworks against the same etcd is likely suicide anyway.

**Comment by jdef** [comment]
this is likely very hard given that k8s assumes control over iptables upon the slave it runs

**Comment by jdef** [comment]
closing this out; the issue of running multiple k8sm frameworks on the same mesos cluster is very complicated and this issue doesn't come anywhere close to capturing the complexity.
