### ISSUE TITLE
Upgrade DCOS Kubernetes package to 1.0

### ISSUE THREAD

**Issue by tsenart** [mesosphere/kubernetes-mesos#371]
* [x] Update flags in km binary invocations found in `bootstrap.sh`
* [x] Revise required ports in `config.json` and `marathon.json` found in https://github.com/mesosphere/universe/blob/version-1.x/repo/packages/K/kubernetes/
* [x] Investigate process for Universe K8S package upgrade/versioning.
* [x] Rebuild
* [x] new kubectl binaries
* [x] update https://docs.mesosphere.com/services/kubernetes/
* [x] update kube-dns templates to v1
  - https://github.com/mesosphere/kubernetes-mesos/tree/master/hack/images/dns
* [x] smoke test new package
  - with and without kube-dns enabled (see docs for how to enable)
  - smoke test with guestbook
* [x] Update package in Universe
  - Change version scheme to something sane
* [x] Release by pushing new Docker image to Dockerhub.
* [x] update etcd to whatever upstream/master has standardized on

/cc @jdef 

Blockers in v1.0.3-v0.6.3-alpha (mark done after they've been cherry picked into the v1.0-v0.6 branch):
- [x] #454 - iptables not in PATH
- [x] #455 - upgrade to kube-ui v2
- [x] #458 - minion must propagate signals
- [x] #459 - kubelet-executor busy looping at shutdown
- [x] #461 - needs flags to disable user-specified pod-task resource constraints
- [x] #462 - kube-proxy in the wrong resource container
- [x] #466 - k8sm reconciliation killing pods in non-default namespace
- [x] #474- upstream bug fixes between v1.0.3 - v1.0.5
- [x] #480 - executors are killed because of OOM

**Comment by sttts** [comment]
Any blockers beside time to continue with this ticket?

**Comment by tsenart** [comment]
Nope, I'll try to get this done tomorrow. What revision of k8s should we base this on?

**Comment by sttts** [comment]
We should make a list what we really want to see in this k8s 1.0 version for dcos. We have some open ends we didn't manage to get into v1 upstream and some things are broken due to that. Let's put that on the agenda for tomorrow.

I would really like to see an automated or at least documented path to new DCOS packages. Would be awesome to have nightly builds via teamcity.

**Comment by tsenart** [comment]
@sttts: Full support on automated package builds, but I think that shall be a different issue that this one.

**Comment by sttts** [comment]
Sure. It's another issue. But it makes the decision much easier which revision to base on.

Main question: what's the goal of the 1.0(-pre) dcos package? When will it be superseded? What are the quality expectations? Is it only a snapshot with known issues? Or are we working towards a real milestone release which is more or less usable?

**Comment by tsenart** [comment]
When we started working on this, K8S 1.0 wasn't out yet. Hence the `pre` suffix. If we have a 1.0 release, then we should base this package on that. The state of this package would still be *alpha* within the DCOS certification scope. We most certainly will be working towards a production ready DCOS K8S package, but this issue isn't related to that. We only started this because we though we would need it for Gophercon, but it turned out we didn't. So, perhaps, it's better to hold off on this until we have more clear requirements, tentatively tomorrow.

**Comment by jdef** [comment]
12-hour soak test with 'resizeFrontend' script, didn't seem to expose any scheduler problems. running w/ 1 master, 5 slaves; package version v1.0.3-v0.6.2

**Comment by sttts** [comment]
Smoke test with guestbook is green.

**Comment by sttts** [comment]
What is left to do? Only testing? Will test https://github.com/mesosphere/kubernetes-mesos/issues/434 now.
