### ISSUE TITLE
Epic: refactor DCOS packages

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#394]
- [x] get rid of executor-install.sh if there is no specific reason for it anymore
- [x] replace s6 by something pre-packaged
- [ ] update DCOS docs to use upstream v1 examples: **done** in https://github.com/mesosphere/mesosphere-docs/pull/131
- [ ] port to Marathon groups as soon as supported by DCOS
- [ ] automate release process via CI with nightly snapshots
- [ ] automate smoke testing
- [ ] split bootstrap.sh into real code and separate templates for service definitions
- [ ] download kubectl from apiserver (compare https://github.com/mesosphere/dcos-kubernetes-cli)
- [ ] deploy ssl certificates and service-account key (compare docker-compose setup)
- [ ] shutdown executors when kubernetes is uninstalled (now pods keep running)
- [x] make framework container work on its own without dcos environment
- [x] use K8SM_MESOS_MASTER to set the mesos.master config. Right now Zookeeper is not used at all.
- [ ] add marathon health checks to all components, not just api-server
- [ ] use upstream build container
- [x] remove copies of dns and kube-ui addon files and use upstream directly: **done** in #397
- [x] add kube-ui: **done** in #397 and https://github.com/mesosphere/universe/pull/187

**Comment by sttts** [comment]
Replaced by milestone https://github.com/mesosphere/kubernetes-mesos/milestones/EPIC:%20refactor%20DCOS%20packages

Closing.
