### ISSUE TITLE
[e2e] some kubectl tests fail

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#400]
conformance:
- [x] Kubectl client Guestbook application should create and stop a working application -  `test/e2e/kubectl.go:140`
- [ ] #485 Kubectl client Kubectl expose should create services for rc - `test/e2e/kubectl.go:364`
- [ ] #486 Kubectl client Update Demo should scale a replication controller - `test/e2e/util.go:861`
- [ ] #486 Kubectl client Update Demo should do a rolling update of a replication controller - `test/e2e/util.go:861`
- [x] Kubectl client Kubectl patch should add annotations for pods in rc - `test/e2e/examples.go:579`

non-conformance:
- [ ] Kubectl client Simple pod should support port-forward - `/test/e2e/kubectl.go:199`

**Comment by sttts** [comment]
Fixed by https://github.com/GoogleCloudPlatform/kubernetes/pull/10390, especially https://github.com/mesosphere/kubernetes/commit/d3131eb56b40540240bdeb8edfffcb7202c11cd0.

**Comment by karlkfi** [comment]
Created specific tickets for the remaining issues: #486 & #485
Ignoring Kubectl client Simple pod should support port-forward unitl conformance tests are passing (now that CI can re-confirm them for us.
