### ISSUE TITLE
Resource related conformance tests fail in non-exclusive Mesos environments

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#489]
This issue tracks e2e conformance tests which are hard for Mesos to pass because k8s is not exclusive user of the cluster:

- [x] ResourceUsage should not exceed expected amount - https://github.com/mesosphere/kubernetes-mesos/issues/439
- [x] Ask kubelet to report container resource usage - https://github.com/mesosphere/kubernetes-mesos/issues/436

  **Analysis summary:** the e2e tests expect hardcoded cgroups "/docker-daemon", "/kubelet", "/kube-proxy", "/system" to be used by the kubelet, the started containers, the docker daemon and the proxy.

- [ ] Enforce pod resource limits - https://github.com/mesosphere/kubernetes-mesos/issues/437

  **Analysis summary:** the e2e test expects that all reported resources are available exclusively. Mesos though accounts for infrastructure resources, namely the Executor, kubelet and proxy as well => the test can launch one or two pods less.

  We have an ugly workaround, documented in https://github.com/mesosphere/kubernetes-mesos/issues/437#issuecomment-140434718.

**Comment by bgrant0607** [comment]
cc @kubernetes/goog-node

**Comment by bgrant0607** [comment]
cc @dchen1107 @vishh

**Comment by vishh** [comment]
@sttts: IIUC if kubelet where to use a root cgroup path for the purposes of capacity, machine configuration and runtime, that would satisfy mesos. Unless kubelet is controlling the `/`(root) cgroup, it should not move system processes into a separate cgroup. cAdvisor libraries are used for machine capacity. So that has to be updated as well.
Personally, I think that is a very useful feature. Is it possible to post a PR for this? 
I assume mesos runs separate docker daemon and kube-proxy instances along with the kubelet?

**Comment by dchen1107** [comment]
No, please don't make cAdvisor lie about the machine capacity. cAdvisor should be the source of the true on computing resource. 

But I do plan to introduce a new concept called MachineAllocable by introduce a flag called machine_reserve to Borglet. This flag should serve the same purpose what @sttts purposed. For Kubernetes 1.0 release, I introduced "/docker-daemon", "/kubelet", "/kube-proxy", "/system" raw containers, so that we could monitor their resource usage pattern. In a long run, we could cap their usage under certain limit / request through --machine_reserve. Is this ok with you?

**Comment by karlkfi** [comment]
I think what you're suggesting, @dchen1107, is actually the inverse of what we want.

We don't want to say "k8s can have everything except X", we want to say "k8s can only have X".

The problem is that k8s thinks it owns all of the node's resources, but when deployed on top of another containerizing system (like say mesos or systemd) the parent system actually owns the resources and hands them out to k8s. 

Mesos-slave does something similar by default, auto-detecting the resources and assuming it can hand them all out, but it has an optional configuration flag that allows you to specify the resources that the slave can give out. 

If k8s had something similar, then that might satisfy the need.

**Comment by karlkfi** [comment]
If the above were implemented, the test to verify enforcement wouldn't ask cAdvisor or the sytem how much resources it has and try to use them all up, it would ask k8s itself how much resources it's been configured to use on that node, and then use that up.

**Comment by vishh** [comment]
@karlkfi: IIUC, @dchen1107 is suggesting passing the resources that the kubelet can use via a flag. For example `--machine-allocable="cpu=5,memory=10G,fs=100G"`. This will override the information provided by cAdvisor.

**Comment by dchen1107** [comment]
Ok, all I cared about is introducing MachineAllocable concept to Kubernetes node. We could have flag to tell Kubelet how much for allocation.

**Comment by dchen1107** [comment]
Yes, @vishh :-)

**Comment by karlkfi** [comment]
Thanks for clarifying. 

FWIW, the analogous mesos config options is `--resources=VALUE` - Total consumable resources per slave, in the form `name(role):value;name(role):value`.

When `--resources` is not supplied, mesos auto-detects resources and reserves 1G (or 1/2 of your RAM, if you have less than 2G total) for "system usage" that it does not allocate. That 1G is not currently configurable (independently of using `--resources`), but sounded similar to what you guys were originally proposing.

So I think the `--machine-allocable` you proposed would work (tho we could probably bike shed the name for a while :cactus:).

**Comment by dchen1107** [comment]
I like --machine-allocable too, at least comparing to machine_reserve, which causes confusion anyway.

**Comment by karlkfi** [comment]
If it's a k8s flag, I'd probably recommend `--allocable-resources`.

**Comment by dchen1107** [comment]
Once we introduce Allocable to Node.Status, you can query Kubelet for the total capacity, and how much it reserves, then reserve the rest of resource subtracting some padding for rest of daemons. 

I am always easy with naming thing since I am not good at it. --allocable-resources it is unless someone introduce a better one.

**Comment by sttts** [comment]
@vishh about the cgroups: the Mesos executor already supports a root cgroup which is passed down to the kubelet, the used for the kubelet itself and for system processes like the docker daemon.

The docker daemon is not exclusive for k8s. Hence, its cgroup must not be touched by the kubelet.

I think our main issue is about the e2e tests https://github.com/mesosphere/kubernetes-mesos/issues/439 and https://github.com/mesosphere/kubernetes-mesos/issues/436 themselves. We are happy with what the kubelet (at least instantiated in-process like at the moment) offers. The tests though assume the default cgroups below the / (root) cgroup and check that these are applied. This cannot work in the Mesos case.

**Comment by dchen1107** [comment]
issue https://github.com/kubernetes/kubernetes/issues/13984 was filed against Kubernetes.

**Comment by sttts** [comment]
@vishh the ```--machine-allocable=``` option would work for us. Also being able to change the node object's allocable (or the current capacity) via the apiserver is fine for Mesos. It looks like the latter is not possible right now though:
```
kubectl patch node 192.168.65.209 -p '{"status":{"capacity":{"cpu":"2.5"}}}'
```
has not effect.
