### ISSUE TITLE
Use https from kubectl through the admin router to the apiserver

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#535]
As a user I want to
- have kubectl exec & log to work
- have a secure connection between my local machine and the apiserver.

TODO:
- [x] implement TLS support for the apiserver
- [x] look into the admin router implementation
- [x] prototype a config change to allow SPDY

**Comment by sttts** [comment]
cc @karlkfi

**Comment by sttts** [comment]
If I understand the SPDY support correctly, SPDY depends on HTTPS. To get HTTPS in DCOS we need certificate generation and probably service accounts.

**Comment by sttts** [comment]
Not sure I understood the CM.3 demo correctly: does it bring SSL admin router support?

**Comment by sttts** [comment]
This is blocked until we deploy TLS, service accounts etc.

**Comment by jdef** [comment]
blocked by #555
