### ISSUE TITLE
state.json is going away in mesos v0.26

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#618]
the mesos k8s cloudprovider uses state.json to build a picture of the cluster. "state.json" has been deprecated in favor of "state".

comments in the mesos code indicate that the deprecation cycle will end with mesos v0.26 (to be released soon)

TODO:
- [x] fix mesos-go
  - --(MERGED)-- https://github.com/mesos/mesos-go/pull/220 (mesos 0.26 proto compat)
  - [x] update k8s godeps to include mesos-go/v0.26 support
    - [x] BLOCKED by https://github.com/kubernetes/kubernetes/pull/19794
    - [x] LGTM https://github.com/kubernetes/kubernetes/pull/20094
- [x] fix the Mesos k8s cloud provider
  - --(MERGED)-- https://github.com/kubernetes/kubernetes/pull/19538
  - cherry picked to https://github.com/mesosphere/kubernetes/pull/55
- [x] etcd-mesos
  - --(MERGED)-- https://github.com/mesosphere/etcd-mesos/pull/88

xref https://issues.apache.org/jira/browse/MESOS-2719

**Comment by jdef** [comment]
determine which CM.x release will ship with v0.26

**Comment by jdef** [comment]
looks like CM.5+ since CM.4 will likely be based on mesos v0.25

**Comment by sttts** [comment]
Is this critical for v0.8.0 because CM.6 moves to Mesos 0.26?

**Comment by jdef** [comment]
yes, this is pretty important.

**Comment by sttts** [comment]
Is it Kubernetes only? Or also Mesos-go? Does the Format change as well? Could you take a look at this?

**Comment by jdef** [comment]
i don't think there are format changes, just a name change for the URI.
impacts both k8sm and mesos-go

**Comment by sttts** [comment]
Can we detect the Mesos version and by that choose the file name?

**Comment by jdef** [comment]
perhaps. or, given that the non .json suffixes are the wave of the future,
just try /state first. if 404, then try state.json

**Comment by jdef** [comment]
cherry-picked into v0.7.2
