### ISSUE TITLE
Measure key scheduler metrics in k8sm

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#621]
- [ ] start with empty cluster with n (2, 5, 10, 20) nodes. create rc with busybox pods, saturate cluster by scaling rc to n*40 pods: OVERALL TIME, FAILURE RATE
- [ ] start another rc with slightly modified pods, do a rolling update of the old to the new rc: OVERALL TIME
- [ ] shutdown the rc: OVERALL TIME UNTIL ALL PODS ARE GONE
- [ ] get the same metrics for upstream k8s, e.g. on GCE
- [ ] get the same metrics for GKE k8s

**Comment by sttts** [comment]
Merging with https://github.com/mesosphere/kubernetes-mesos-private/issues/27
