### ISSUE TITLE
Blog about the v0.7 (k8s 1.1) release & k8s 1.1 conformance

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#622]
- [x] create shared Google docs: https://docs.google.com/document/d/1LEFss0cxyeNG5kjWesIZRn2ld1nc9VFGBsrurijAd1Y/edit
- [x] create outline
- write paragraphs/sections
  - [x] Kubernetes 1.1
  - [x] conformant to Kubernetes 1.1 with cluster/mesos/docker vs. DCOS package
  - [x] dcos kubectl – k8s on a slide
  - [x] etcd-mesos
  - [x] Quality assurance and being part of the k8s dev process
  - [x] road ahead
- [x] internal review
- [x] review by @mhausenblas 
- [ ] get the "GO" by Derrick

**Comment by sttts** [comment]
Moving into soon for the moment. We can bump it up again next week when the actually code changes are done.

**Comment by sttts** [comment]
Started with an outline.

**Comment by sttts** [comment]
Written and reviewed by @jdef.

**Comment by sttts** [comment]
Being reviewed by the mesosphere docs team: https://mesosphere.atlassian.net/browse/DOCS-410

**Comment by karlkfi** [comment]
Final post is ready for review, @sttts See JIRA for link.

**Comment by sttts** [comment]
https://mesosphere.com/blog/2015/12/04/kubernetes-mesos-0-7-0/
