### ISSUE TITLE
k8s dashboard doesn't display cpu, memory

### ISSUE THREAD

**Issue by s-urbaniak** [mesosphere/kubernetes-mesos#669]
The k8s dashboard doesn't display cpu/memory utilization.

1. start k8s using `./cluster/kube-up.sh`
2. open https://MASTER_IP:6443/api/v1/proxy/namespaces/kube-system/services/kube-ui/#/dashboard/

You can see that these bars do not update cpu/memory utilization.

TODO:
- [x] wait for merge of kubernetes/kube-ui#44
- [x] wait for merge of kubernetes/kubernetes#18349
- [x] wait for kube-ui v4 image and activate that in the k8s addon

**Comment by s-urbaniak** [comment]
![screenshot from 2015-12-05 13-54-37](https://cloud.githubusercontent.com/assets/375856/11607879/6acbc2ea-9b58-11e5-8128-64ce7edb4688.png)

**Comment by s-urbaniak** [comment]
kube-ui calls "https://MASTER_IP:6443/api/v1/nodes" returning iffy data:
```
{
  "kind": "NodeList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/nodes",
    "resourceVersion": "284"
  },
  "items": [
    {
      "metadata": {
        "name": "172.17.0.7",
...
      "status": {
        "capacity": {
          "cpu": "0",
          "memory": "448Mi",
          "pods": "40"
        },
...
```

**Comment by karlkfi** [comment]
The dashboard has worked in the past. Did it only recently stop working?

**Comment by s-urbaniak** [comment]
@karlkfi yes, it suddenly stopped working, I recognized this while testing locally

**Comment by s-urbaniak** [comment]
kube-ui switched from v2 to v3 https://github.com/kubernetes/kubernetes/commit/2b22b252f3c2db17290424d428fb9a5f8d932924

Reverting to kube-ui v2 shows correct behaviour:

<img width="735" alt="screen shot 2015-12-07 at 12 54 45" src="https://cloud.githubusercontent.com/assets/375856/11626292/f1043c72-9ce1-11e5-8933-722c651b5742.png">

**Comment by sttts** [comment]
Looking into the JavaScript code.

**Comment by sttts** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/18349 and https://github.com/kubernetes/kube-ui/pull/44.

**Comment by sttts** [comment]
Moving this to v0.7.2 because v1.1.3 is not broken (which will be the v0.7.1 baseline). It still uses the v2 image of kube-ui.

**Comment by karlkfi** [comment]
Looking like kube-ui is actually borked on v0.7.1, but maybe not for the same reason. Does kube-ui v3 have other fixes we need to pick up? See #703

**Comment by jdef** [comment]
we're waiting on google for this, perhaps ping mike danese

**Comment by jdef** [comment]
v4 was pushed https://github.com/kubernetes/kubernetes/commit/b660cf9596149b23df4dd3df1f2d1e0bf9f5f2ce

**Comment by jdef** [comment]
nothing to cherry-pick here, v0.7.2 has both of these changes, picked up kube-ui v4 from rebase to latest release-1.1
