### ISSUE TITLE
inject metadata to support mesos container GC

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#739]
As Mesos I want to be able to terminate pod containers that are orphans of an Executor process that's no longer running on the agent node.

Strategy: tag all docker containers with an envvar `MESOS_EXECUTOR_CONTAINER_UUID` and let a Mesos module garbage collect docker containers tagged with a container-id that the Mesos agent no longer recognizes as valid.

- [x] upstream labels PR: https://github.com/kubernetes/kubernetes/pull/19881
  - REJECTED: need to use envvars instead
- [x] proposed envvars for pod infra container: 
  - MERGED: https://github.com/kubernetes/kubernetes/pull/20719
- [x] k8sm support for injecting envvars int o all containers
  - MERGED :: https://github.com/kubernetes/kubernetes/pull/20845

**Comment by jdef** [comment]
Will likely have to implement using environment variables instead of Docker CT labels since k8s wants to rip out support for labels in favor of a local state checkpoint mechanism (which is opaque to mesos GC).

**Comment by jdef** [comment]
Even if we injected envvar's into user containers, we'd need to do the same for pod-infra containers and there's no API to support that. Have asked Google for feedback.

**Comment by jdef** [comment]
Received buy-in from google re: mods to kubelet to support envvar injection into pod infra CT. Need to code it up!

**Comment by jdef** [comment]
Awaiting response from Google re: envvars PR

**Comment by jdef** [comment]
update: Google approved envvar injection upstream API change. currently working to add the actual injection into the k8sm executor

**Comment by jdef** [comment]
we have liftoff! via the PR from 20845 above:
```
# docker inspect 117b59675c81 31af5052f8c6 ddb25c42a661 051788adadff |grep -A1 -B1 -e MESOS_EXEC
        "Env": [
            "MESOS_EXECUTOR_CONTAINER_UUID=9908d6b5-408f-45ea-92ad-1dfdf687b061",
            "KUBERNETES_DASHBOARD_SERVICE_HOST=10.10.10.8",
--
        "Env": [
            "MESOS_EXECUTOR_CONTAINER_UUID=9908d6b5-408f-45ea-92ad-1dfdf687b061",
            "KUBERNETES_PORT_443_TCP_PORT=443",
--
        "Env": [
            "MESOS_EXECUTOR_CONTAINER_UUID=9908d6b5-408f-45ea-92ad-1dfdf687b061",
            "KUBERNETES_PORT_443_TCP_ADDR=10.10.10.1",
--
        "Env": [
            "MESOS_EXECUTOR_CONTAINER_UUID=9908d6b5-408f-45ea-92ad-1dfdf687b061",
            "KUBERNETES_PORT_443_TCP_PORT=443",
```

this shows:
* two pod infra containers
* one user container from a static pod
* one user container from a replication controlled pod
